spring.application.name=QuickCart
server.port=8081

# Controls Verbosity
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

spring.profiles.active=dev

spring.datasource.url=jdbc:h2:mem:QuickCart
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true