spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: qC_siddhesh_9fA7xL2pQw8ZrT6mN4vYkH1uB3eD5Jc
  expiration: 86400000
