spring.application.name=QuickCart
server.port=8081

# ?????????????????????????????????????????
# LOGGING
# ?????????????????????????????????????????
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

spring.profiles.active=default

# ?????????????????????????????????????????
# DATABASE - PostgreSQL
# ?????????????????????????????????????????
# update = alters tables to match entities (dev only)
# validate = only checks schema, no changes (prod)
# create-drop = wipes DB on restart (testing only)
spring.datasource.url=jdbc:postgresql://localhost:5432/quickcart
spring.datasource.username=quickcart_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ?????????????????????????????????????????
# SQL INIT
# ?????????????????????????????????????????
# Runs data.sql on startup, JPA tables created first
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ?????????????????????????????????????????
# JWT
# ?????????????????????????????????????????
# Use env variable in prod: jwt.secret=${JWT_SECRET}
# Expiry in ms ? 3600000 = 1 hour
jwt.secret=my-super-secret-key-my-super-secret-key
jwt.expiration=3600000

# ?????????????????????????????????????????
# KAFKA
# ?????????????????????????????????????????
# Kafka broker address (from docker-compose)
spring.kafka.bootstrap-servers=localhost:9092

# Producer: converts Java object ? JSON string ? bytes before sending
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer group: instances with same group-id share message load
# earliest = read from beginning if no offset found (dev)
# latest = only new messages after startup (prod)
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer